Style/MultilineBlockChain:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

# We have squiggly heredocs
Layout/IndentHeredoc:
  Enabled: false

Style/AndOr:
  Enabled: false

Metrics/LineLength:
  Max: 120
